"""
Service for formatting and posting review comments
"""
import structlog
from typing import List
from models import ReviewResult, ReviewIssue, IssueSeverity

logger = structlog.get_logger()


class CommentService:
    """Format review results as comments"""
    
    SEVERITY_EMOJI = {
        IssueSeverity.CRITICAL: "🔴",
        IssueSeverity.HIGH: "🟠",
        IssueSeverity.MEDIUM: "🟡",
        IssueSeverity.LOW: "🔵",
        IssueSeverity.INFO: "ℹ️",
    }
    
    @staticmethod
    def format_summary_comment(result: ReviewResult) -> str:
        """
        Format review result as a summary comment
        
        Args:
            result: ReviewResult to format
            
        Returns:
            Markdown formatted comment
        """
        # Header
        lines = [
            "## 🤖 AI Code Review",
            "",
            f"**Score:** {result.score}/10 {'✅' if result.score >= 8 else '⚠️' if result.score >= 6 else '❌'}",
            "",
        ]
        
        # Summary
        lines.extend([
            "### 📝 Summary",
            result.summary,
            "",
        ])
        
        # Statistics
        if result.total_issues > 0:
            lines.extend([
                "### 📊 Issues Found",
                f"- Total: **{result.total_issues}**",
            ])
            
            if result.critical_count > 0:
                lines.append(f"- {CommentService.SEVERITY_EMOJI[IssueSeverity.CRITICAL]} Critical: **{result.critical_count}**")
            if result.high_count > 0:
                lines.append(f"- {CommentService.SEVERITY_EMOJI[IssueSeverity.HIGH]} High: **{result.high_count}**")
            if result.medium_count > 0:
                lines.append(f"- {CommentService.SEVERITY_EMOJI[IssueSeverity.MEDIUM]} Medium: **{result.medium_count}**")
            if result.low_count > 0:
                lines.append(f"- {CommentService.SEVERITY_EMOJI[IssueSeverity.LOW]} Low: **{result.low_count}**")
            if result.info_count > 0:
                lines.append(f"- {CommentService.SEVERITY_EMOJI[IssueSeverity.INFO]} Info: **{result.info_count}**")
            
            lines.append("")
        
        # Critical and High issues detail
        critical_high = [i for i in result.issues if i.severity in [IssueSeverity.CRITICAL, IssueSeverity.HIGH]]
        if critical_high:
            lines.extend([
                "### ⚠️ Important Issues",
                "",
            ])
            
            for issue in critical_high[:10]:  # Limit to 10
                emoji = CommentService.SEVERITY_EMOJI[issue.severity]
                lines.extend([
                    f"#### {emoji} {issue.title}",
                    f"**Severity:** {issue.severity.value.upper()}  ",
                    f"**Category:** {issue.category}  ",
                ])
                
                if issue.file_path:
                    location = f"`{issue.file_path}`"
                    if issue.line_number:
                        location += f" (Line {issue.line_number})"
                    lines.append(f"**Location:** {location}  ")
                
                lines.extend([
                    "",
                    issue.description,
                    "",
                ])
                
                if issue.suggestion:
                    lines.extend([
                        "**Suggestion:**",
                        f"> {issue.suggestion}",
                        "",
                    ])
        
        # Recommendation
        lines.extend([
            "### 🎯 Recommendation",
            "",
        ])
        
        if result.block_merge:
            lines.append("❌ **Do not merge** - Critical issues must be fixed first.")
        elif result.approval_recommended:
            lines.append("✅ **Approved** - Code looks good!")
        else:
            lines.append("⚠️ **Review recommended** - Please address the issues above.")
        
        lines.extend([
            "",
            "---",
            "*Generated by Mennan MCP Server*"
        ])
        
        return "\n".join(lines)
    
    @staticmethod
    def format_inline_comment(issue: ReviewIssue) -> str:
        """
        Format a single issue as an inline comment
        
        Args:
            issue: ReviewIssue to format
            
        Returns:
            Markdown formatted inline comment
        """
        emoji = CommentService.SEVERITY_EMOJI[issue.severity]
        
        lines = [
            f"{emoji} **{issue.severity.value.upper()}: {issue.title}**",
            "",
            issue.description,
        ]
        
        if issue.suggestion:
            lines.extend([
                "",
                "**Suggestion:**",
                f"> {issue.suggestion}"
            ])
        
        lines.extend([
            "",
            f"*Category: {issue.category}*"
        ])
        
        return "\n".join(lines)
    
    @staticmethod
    def format_inline_comments(result: ReviewResult) -> List[dict]:
        """
        Format issues as inline comments with file and line info
        
        Args:
            result: ReviewResult
            
        Returns:
            List of inline comment data
        """
        comments = []
        
        for issue in result.issues:
            if issue.file_path and issue.line_number:
                comments.append({
                    'file_path': issue.file_path,
                    'line': issue.line_number,
                    'body': CommentService.format_inline_comment(issue)
                })
        
        return comments

