# Bitbucket Pipelines - AI Code Review (Working Version)
# Repository: https://bitbucket.org/commencers/playground

image: atlassian/default-image:3

pipelines:
  pull-requests:
    '**':
      - step:
          name: AI Code Review
          script:
            - echo "AI Code Review baslatiliyor..."
            - echo "PR ID:" $BITBUCKET_PR_ID
            - echo "Branch:" $BITBUCKET_BRANCH
            
            # Create properly formatted JSON payload
            - |
              cat > /tmp/payload.json << 'JSONEOF'
              {
                "pullrequest": {
                  "id": PLACEHOLDER_PR_ID,
                  "title": "PLACEHOLDER_TITLE",
                  "description": "",
                  "links": {
                    "html": {
                      "href": "PLACEHOLDER_URL"
                    }
                  },
                  "source": {
                    "branch": {
                      "name": "PLACEHOLDER_SOURCE"
                    }
                  },
                  "destination": {
                    "branch": {
                      "name": "PLACEHOLDER_DEST"
                    }
                  },
                  "author": {
                    "username": "bitbucket-user"
                  }
                },
                "repository": {
                  "full_name": "commencers/playground",
                  "uuid": "PLACEHOLDER_UUID",
                  "workspace": {
                    "slug": "commencers"
                  }
                }
              }
              JSONEOF
            
            # Replace placeholders with actual values (using # as delimiter to avoid conflicts with /)
            - sed -i "s#PLACEHOLDER_PR_ID#$BITBUCKET_PR_ID#g" /tmp/payload.json
            - sed -i "s#PLACEHOLDER_TITLE#PR $BITBUCKET_PR_ID#g" /tmp/payload.json
            - sed -i "s#PLACEHOLDER_URL#https://bitbucket.org/commencers/playground/pull-requests/$BITBUCKET_PR_ID#g" /tmp/payload.json
            - sed -i "s#PLACEHOLDER_SOURCE#$BITBUCKET_BRANCH#g" /tmp/payload.json
            - sed -i "s#PLACEHOLDER_DEST#$BITBUCKET_PR_DESTINATION_BRANCH#g" /tmp/payload.json
            - sed -i "s#PLACEHOLDER_UUID#$BITBUCKET_REPO_UUID#g" /tmp/payload.json
            
            # Show payload for debugging
            - echo "Payload:"
            - cat /tmp/payload.json
            
            # Send webhook request
            - |
              HTTP_CODE=$(curl -s -o /tmp/response.txt -w "%{http_code}" \
                -X POST "$REVIEW_SERVER_URL/webhook" \
                -H "Content-Type: application/json" \
                -H "X-Event-Key: pullrequest:created" \
                --data-binary @/tmp/payload.json)
              echo "HTTP Status: $HTTP_CODE"
              echo "Response:"
              cat /tmp/response.txt
              if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
                echo "✅ AI Code Review basariyla tamamlandi!"
                exit 0
              else
                echo "⚠️  AI Code Review uyari ile tamamlandi (HTTP: $HTTP_CODE)"
                exit 0
              fi

