name: AI Code Review with MCP Server

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install MCP Server Dependencies
        run: |
          pip install --upgrade pip
          pip install groq pygithub pyyaml python-dotenv structlog unidiff
      
      - name: Get PR Diff
        id: diff
        run: |
          # Base branch'i fetch et
          git fetch origin ${{ github.event.pull_request.base.ref }}
          
          # Diff'i al ve filtrele
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD \
            -- ${{ env.REVIEW_INCLUDE_PATTERNS }} \
            > pr_diff.txt
          
          # Diff boyutunu kontrol et
          DIFF_SIZE=$(wc -c < pr_diff.txt)
          echo "diff_size=$DIFF_SIZE" >> $GITHUB_OUTPUT
          
          if [ $DIFF_SIZE -gt ${{ env.REVIEW_MAX_PATCH_BYTES }} ]; then
            echo "⚠️ Diff size ($DIFF_SIZE bytes) exceeds limit (${{ env.REVIEW_MAX_PATCH_BYTES }} bytes)"
            echo "diff_too_large=true" >> $GITHUB_OUTPUT
          else
            echo "diff_too_large=false" >> $GITHUB_OUTPUT
          fi
        env:
          REVIEW_MAX_PATCH_BYTES: ${{ secrets.REVIEW_MAX_PATCH_BYTES || '350000' }}
          REVIEW_INCLUDE_PATTERNS: ${{ secrets.REVIEW_INCLUDE_PATTERNS || '**/*.cs **/*.ts **/*.js **/*.py **/*.java **/*.go **/*.rb **/*.rs **/*.cpp **/*.h **/*.csproj **/*.sln **/*.yml **/*.yaml' }}
      
      - name: Run AI Code Review
        if: steps.diff.outputs.diff_too_large != 'true'
        id: review
        run: |
          python << 'PYTHON_SCRIPT'
          import os
          import asyncio
          from groq import Groq
          import json
          
          async def review_code():
              # Groq client oluştur
              client = Groq(api_key=os.getenv("GROQ_API_KEY"))
              
              # Diff'i oku
              with open("pr_diff.txt", "r") as f:
                  diff = f.read()
              
              if not diff.strip():
                  print("No changes to review")
                  return None
              
              # Review prompt
              prompt = f"""You are an expert code reviewer. Analyze the following code changes and provide detailed feedback.

          Focus areas: security, performance, bugs, code quality, best practices

          Code diff:
          {diff[:10000]}

          Provide your review in JSON format:
          {{
              "summary": "Brief overview",
              "score": 8,
              "issues": [
                  {{
                      "severity": "critical|high|medium|low|info",
                      "title": "Issue title",
                      "description": "Detailed description",
                      "file_path": "path/to/file",
                      "line_number": 42,
                      "suggestion": "How to fix"
                  }}
              ],
              "approval_recommended": true,
              "block_merge": false
          }}"""
              
              # Groq API çağrısı
              response = client.chat.completions.create(
                  model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
                  messages=[
                      {"role": "system", "content": "You are an expert code reviewer."},
                      {"role": "user", "content": prompt}
                  ],
                  temperature=0.3,
                  max_tokens=4096
              )
              
              result = response.choices[0].message.content
              
              # JSON parse
              try:
                  start = result.find('{')
                  end = result.rfind('}') + 1
                  if start != -1 and end > start:
                      review_json = json.loads(result[start:end])
                      return review_json
              except:
                  pass
              
              return {
                  "summary": result[:500],
                  "score": 7,
                  "issues": [],
                  "approval_recommended": True
              }
          
          # Run review
          result = asyncio.run(review_code())
          
          if result:
              # Sonuçları dosyaya yaz
              with open("review_result.json", "w") as f:
                  json.dump(result, f, indent=2)
              
              print(f"Review completed: Score {result.get('score', 0)}/10")
              print(f"Issues found: {len(result.get('issues', []))}")
          else:
              print("No review needed")
          PYTHON_SCRIPT
        env:
          AI_PROVIDER: ${{ secrets.AI_PROVIDER || 'groq' }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL: ${{ secrets.GROQ_MODEL || 'llama-3.3-70b-versatile' }}
      
      - name: Format Review Comment
        if: steps.diff.outputs.diff_too_large != 'true'
        id: format
        run: |
          python << 'PYTHON_SCRIPT'
          import json
          import os
          
          # Review sonucunu oku
          if not os.path.exists("review_result.json"):
              exit(0)
          
          with open("review_result.json", "r") as f:
              review = json.load(f)
          
          # Markdown comment oluştur
          score = review.get("score", 0)
          score_emoji = "🔴" if score < 5 else "🟡" if score < 8 else "🟢"
          
          comment = f"""## 🤖 AI Code Review
          
          **Score:** {score}/10 {score_emoji}
          
          ### 📝 Summary
          {review.get('summary', 'No summary available')}
          
          ### 📊 Issues Found
          """
          
          issues = review.get('issues', [])
          if issues:
              # Severity counts
              critical = sum(1 for i in issues if i.get('severity') == 'critical')
              high = sum(1 for i in issues if i.get('severity') == 'high')
              medium = sum(1 for i in issues if i.get('severity') == 'medium')
              low = sum(1 for i in issues if i.get('severity') == 'low')
              
              comment += f"""- Total: **{len(issues)}**
          - 🔴 Critical: **{critical}**
          - 🟠 High: **{high}**
          - 🟡 Medium: **{medium}**
          - 🔵 Low: **{low}**
          
          ### ⚠️ Issues Details
          
          """
              
              for i, issue in enumerate(issues[:5], 1):  # İlk 5 issue
                  severity_emoji = {
                      'critical': '🔴',
                      'high': '🟠',
                      'medium': '🟡',
                      'low': '🔵',
                      'info': 'ℹ️'
                  }.get(issue.get('severity', 'info'), 'ℹ️')
                  
                  comment += f"""#### {severity_emoji} {i}. {issue.get('title', 'Issue')}
          
          **Severity:** {issue.get('severity', 'unknown').upper()}  
          **Location:** `{issue.get('file_path', 'N/A')}` (Line: {issue.get('line_number', 'N/A')})
          
          {issue.get('description', 'No description')}
          
          """
                  
                  if issue.get('suggestion'):
                      comment += f"""**💡 Suggestion:**
          > {issue.get('suggestion')}
          
          """
              
              if len(issues) > 5:
                  comment += f"\n_... and {len(issues) - 5} more issues_\n"
          else:
              comment += "- No issues found! ✅\n"
          
          comment += f"""
          ---
          
          **Recommendation:** {'✅ Approved' if review.get('approval_recommended') else '⚠️ Needs attention'}  
          **Block Merge:** {'❌ Yes' if review.get('block_merge') else '✅ No'}
          
          <sub>Powered by MCP Server with Groq ({os.getenv('GROQ_MODEL', 'llama-3.3-70b-versatile')})</sub>
          """
          
          # Comment'i dosyaya yaz (GitHub Actions için)
          with open("review_comment.md", "w") as f:
              f.write(comment)
          
          print("Comment formatted successfully")
          PYTHON_SCRIPT
        env:
          GROQ_MODEL: ${{ secrets.GROQ_MODEL || 'llama-3.3-70b-versatile' }}
      
      - name: Post Review Comment
        if: steps.diff.outputs.diff_too_large != 'true' && hashFiles('review_comment.md') != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review_comment.md', 'utf8');
            
            // Önceki bot yorumlarını bul
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(c => 
              c.user.type === 'Bot' && c.body.includes('🤖 AI Code Review')
            );
            
            // Varsa güncelle, yoksa yeni oluştur
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
              console.log('Updated existing comment');
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
              console.log('Created new comment');
            }
      
      - name: Handle Large Diff
        if: steps.diff.outputs.diff_too_large == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `## 🤖 AI Code Review
            
            ⚠️ **Warning:** The PR diff is too large for automatic review.
            
            **Diff Size:** ${context.payload.pull_request.additions + context.payload.pull_request.deletions} lines
            **Maximum:** ${{ secrets.REVIEW_MAX_PATCH_BYTES || '350000' }} bytes
            
            Please consider:
            - Breaking this PR into smaller, focused changes
            - Reviewing critical files manually
            - Using \`git diff\` locally for full review
            
            <sub>Powered by MCP Server</sub>
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
      
      - name: Review Complete
        run: |
          echo "✅ AI Code Review completed successfully!"
          echo "📊 Check the PR comments for detailed feedback"

