"""
Detailed template — expanded review with code snippets, all severity levels,
file-by-file breakdown, and full suggestion blocks.
"""

from __future__ import annotations

from models import ReviewResult, ReviewIssue, IssueSeverity
from review_templates.base import (
    BaseTemplate,
    SEVERITY_EMOJI,
    CATEGORY_TYPE_MAP,
    score_icon,
)


class DetailedTemplate(BaseTemplate):
    name = "detailed"
    description = "Genişletilmiş review — tüm issue'lar, kod snippet'leri, dosya bazlı dağılım"

    def render_summary(
        self,
        result: ReviewResult,
        *,
        show_detailed_table: bool = False,
    ) -> str:
        lines = [
            "## 🔍 MCP AI Code Review — Detailed Report",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| **Quality Score** | {result.score}/10 {score_icon(result.score)} |",
            f"| **Total Issues** | {result.total_issues} |",
            f"| **Critical** | {result.critical_count} |",
            f"| **High** | {result.high_count} |",
            f"| **Medium** | {result.medium_count} |",
            f"| **Low** | {result.low_count} |",
            f"| **Info** | {result.info_count} |",
            f"| **Merge Recommendation** | {'❌ BLOCK' if result.block_merge else '✅ OK' if result.approval_recommended else '⚠️ REVIEW'} |",
            "",
        ]

        if show_detailed_table:
            lines.append(self._severity_type_table(result))

        lines.extend(["### 📝 Summary", "", result.summary, ""])

        # --- File-by-file breakdown ---
        file_issues: dict[str, list[ReviewIssue]] = {}
        no_file_issues: list[ReviewIssue] = []
        for issue in result.issues:
            if issue.file_path:
                file_issues.setdefault(issue.file_path, []).append(issue)
            else:
                no_file_issues.append(issue)

        if file_issues:
            lines.extend(["### 📂 File-by-File Breakdown", ""])
            for fpath in sorted(file_issues):
                issues = file_issues[fpath]
                sev_counts = {}
                for i in issues:
                    sev_counts[i.severity.value] = sev_counts.get(i.severity.value, 0) + 1
                badge = " ".join(f"{SEVERITY_EMOJI.get(IssueSeverity(s), '')} {c}" for s, c in sev_counts.items())
                lines.extend([f"<details>", f"<summary><code>{fpath}</code> — {len(issues)} issue(s) ({badge})</summary>", ""])

                for issue in issues:
                    emoji = SEVERITY_EMOJI[issue.severity]
                    lines.extend([
                        f"#### {emoji} {issue.title}",
                        "",
                        f"| Field | Detail |",
                        f"|-------|--------|",
                        f"| **Severity** | {issue.severity.value.upper()} |",
                        f"| **Category** | {issue.category} |",
                    ])
                    if issue.line_number:
                        end = f"-{issue.line_end}" if issue.line_end else ""
                        lines.append(f"| **Line** | {issue.line_number}{end} |")
                    lines.extend(["", issue.description, ""])

                    if issue.code_snippet:
                        lines.extend(["**Problematic code:**", f"```", issue.code_snippet, "```", ""])

                    if issue.suggestion:
                        lines.extend(["**Suggestion:**", f"> {issue.suggestion}", ""])

                    lines.append("---")
                    lines.append("")

                lines.extend(["</details>", ""])

        if no_file_issues:
            lines.extend(["### 📋 General Issues (no specific file)", ""])
            for issue in no_file_issues:
                emoji = SEVERITY_EMOJI[issue.severity]
                lines.extend([
                    f"- {emoji} **{issue.severity.value.upper()}** — {issue.title}: {issue.description[:120]}{'...' if len(issue.description) > 120 else ''}",
                ])
            lines.append("")

        # --- Recommendation ---
        lines.extend(["### 🎯 Recommendation", ""])
        if result.block_merge:
            lines.append("❌ **Do not merge** — Critical issues must be resolved before merging.")
        elif result.approval_recommended:
            lines.append("✅ **Approved** — No blocking issues found.")
        else:
            lines.append("⚠️ **Changes requested** — Please address the issues listed above.")

        lines.extend([
            "",
            "---",
            "*Generated by MCP AI Code Review Server — Detailed Template*",
            f"*Review Score: {result.score}/10*",
        ])
        return "\n".join(lines)

    # ------------------------------------------------------------------

    @staticmethod
    def _severity_type_table(result: ReviewResult) -> str:
        overall = {t: {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0} for t in ("Security", "Maintainability", "Reliability")}
        for issue in result.issues:
            if issue.severity not in (IssueSeverity.CRITICAL, IssueSeverity.HIGH, IssueSeverity.MEDIUM):
                continue
            itype = CATEGORY_TYPE_MAP.get(issue.category.lower(), "Maintainability")
            overall[itype][issue.severity.value.upper()] += 1

        lines = [
            "### 📊 Severity × Type Matrix",
            "",
            "| Type | 🔴 Critical | 🟠 High | 🟡 Medium | Total |",
            "|------|:---:|:---:|:---:|:---:|",
        ]
        for t in ("Security", "Reliability", "Maintainability"):
            c, h, m = overall[t]["CRITICAL"], overall[t]["HIGH"], overall[t]["MEDIUM"]
            lines.append(f"| **{t}** | {c} | {h} | {m} | {c + h + m} |")
        lines.append("")
        return "\n".join(lines)
